### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by simleb** [simleb/clinfo#1]
The current plan for improvements is:
- [x] support OpenCL 1.2 variables
- [x] refactor to make more DRY
- [x] query a specific variable
- [x] query a specific platform and/or device
- [x] print either pretty or raw output

I'm just writing it there for future reference.
